import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Banner from '../components/banner'


// A font being used for tite:  
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const handleOnBannerBtnClick = () => {
    console.log("hi banner button")
  }
  
  return (
    <>
    
      <Head>
        <title>Drink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/coffee-bean-16.ico" />
      </Head>
      
      <main className={styles.main}>      
        {/* <h1 className={inter.className}>Drink.io</h1> */}
      </main>
      <Banner buttonText="View store nearby" handleOnClick={handleOnBannerBtnClick}/>   
    </>
  )
}
