import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import coffee from '../public/static/coffee.gif'


// A font being used for tite:  
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Image className={styles.titleimage} src={coffee}  unoptimized={true} />
      
      <main className={styles.main}>      
        <h1 className={inter.className}>Dink.io</h1>
      </main>

      <footer className={styles.footer} ></footer>
    </>
  )
}
